# Generated by Django 2.2.2 on 2019-06-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Confirms',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('item_id', models.IntegerField()),
        #         ('category_id', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Likes',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True,
        #                                 primary_key=True, serialize=False, verbose_name='ID')),
        #         ('item_id', models.IntegerField()),
        #         ('user_id', models.IntegerField()),
        #     ],
        # ),
        # migrations.DeleteModel(
        #     name='Like',
        # ),
    ]
