# Generated by Django 2.2.2 on 2019-06-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0002_auto_20190603_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('img_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(max_length=50)),
                ('category_id', models.IntegerField()),
                ('no_rooms', models.IntegerField()),
                ('no_bathrooms', models.IntegerField()),
                ('surface_area', models.IntegerField()),
                ('furnished', models.CharField(max_length=50)),
                ('location', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('floor_no', models.IntegerField()),
                ('car_make', models.CharField(max_length=50)),
                ('year_manufactured', models.CharField(max_length=50)),
                ('no_killometers', models.IntegerField()),
                ('fuel', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('confirmed', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('location', models.TextField()),
                ('password', models.TextField()),
                ('image_url', models.TextField()),
                ('role', models.CharField(max_length=50)),
                ('confirm', models.CharField(max_length=50)),
            ],
        ),
    ]
