# Generated by Django 2.2.2 on 2019-06-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0002_auto_20190613_1057'),
        ('MobClient', '0002_auto_20190613_0842'),
    ]

    operations = [
    ]
