# Generated by Django 2.2.2 on 2019-06-17 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0003_merge_20190617_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='MobClient.Items'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemss', to='MobClient.Items'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likess', to=settings.AUTH_USER_MODEL),
        ),
    ]
