# Generated by Django 2.2.2 on 2019-06-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0003_categories_images_items_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='Likes',
        ),
    ]
