# Generated by Django 2.2.2 on 2019-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0004_auto_20190606_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='car_make',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='floor_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='fuel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='furnished',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='no_bathrooms',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='no_rooms',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='surface_area',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='transmission',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='year_manufactured',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
