# Generated by Django 2.2.2 on 2019-06-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
