# Generated by Django 2.2.2 on 2019-06-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0005_delete_userprofileinfo'),
        ('MobClient', '0004_auto_20190617_0844'),
    ]

    operations = [
    ]
