# Generated by Django 2.2.2 on 2019-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0006_auto_20190611_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='images',
            field=models.TextField(blank=True),
        ),
    ]
