# Generated by Django 2.2.2 on 2019-06-22 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0007_auto_20190619_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
