# Generated by Django 2.2.2 on 2019-06-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0007_items_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='floor_no',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='no_bathrooms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='no_rooms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='surface_area',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
