# Generated by Django 2.2.2 on 2019-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0008_auto_20190622_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='starsReview',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
