# Generated by Django 2.2.2 on 2019-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0009_auto_20190622_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='starsReview',
            field=models.IntegerField(blank=True),
        ),
    ]
