# Generated by Django 2.2.2 on 2019-06-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0010_auto_20190623_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='MobClient.Items'),
        ),
    ]
