# Generated by Django 2.2.2 on 2019-06-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0010_auto_20190623_1151'),
        ('MobClient', '0010_auto_20190623_1035'),
    ]

    operations = [
    ]
