# Generated by Django 2.2.2 on 2019-06-28 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobClient', '0011_merge_20190628_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='MobClient.Items'),
        ),
    ]
